# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

all:
	make -C ethiopian
	make -C ethiopian-ng
	make -C hello
	make -C heron

clean:
	make clean -C ethiopian
	make clean -C ethiopian-ng
	make clean -C hello
	make clean -C heron
