# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

CXX=g++
CFLAGS=-Wall --pedantic

%.sh.out: %.sh
	cd $$(dirname $<) && bash $$(basename $<) > $$(basename $@)

%: %.cpp
	$(CXX) $(CFLAGS) $^ -o $@
