include ../makefile.common

all: farben.sh.out zahlen.sh.out zahlen2.sh.out zahlen_name.sh.out auto.sh.out auto_einfach.sh.out zahlen-sort.sh.out namen.sh.out

clean:
	$(RM) auto.sh.out
	$(RM) auto_einfach.sh.out
	$(RM) farben.sh.out
	$(RM) namen.sh.out
	$(RM) zahlen-sort.sh.out
	$(RM) zahlen.sh.out
	$(RM) zahlen2.sh.out
	$(RM) zahlen_name.sh.out
