# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

include ../../makefile.common

ethiopian.out: ethiopian
	./$^ 14 36 > $@

ethiopian: ethiopian.cpp

clean:
	$(RM) ethiopian
	$(RM) ethiopian.out
