# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

all: gesellschaft_vierte.pdf

gesellschaft_vierte.pdf: gesellschaft_vierte.tex
	pdflatex $^

clean:
	$(RM) gesellschaft_vierte.aux
	$(RM) gesellschaft_vierte.lof
	$(RM) gesellschaft_vierte.log
	$(RM) gesellschaft_vierte.lot
	$(RM) gesellschaft_vierte.pdf
	$(RM) gesellschaft_vierte.toc
