# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

include ../../makefile.common

bericht.out: bericht
	./bericht ../../Finale/data_abschlussbericht.dat $@

bericht: bericht.cpp

clean:
	$(RM) bericht
